apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-demo
  name: micro-backend-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: backend-demo
  type: NodePort