apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-demo
    env: production
  name: micro-frontend-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: frontend-demo
  type: NodePort